

2022-06-14 00:44:52.231210 -- DBForItems.add_items -- HTTPSConnectionPool(host='www.vremyanamaza.ru', port=443): Max retries exceeded with url: /%D0%A6%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9/%D0%B2%D1%80%D0%B5%D0%BC%D1%8F-%D0%BD%D0%B0%D0%BC%D0%B0%D0%B7%D0%B0-%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0/19400-tat17 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104606350>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) 

2022-06-14 00:45:37.625617 -- DBForItems.add_items -- Class 'builtins.str' is not mapped 

2022-06-14 00:48:18.085178 -- DBForItems.add_items -- Class 'builtins.str' is not mapped 

2022-06-14 03:05:42.402625 -- DBForItem.update_items -- HTTPSConnectionPool(host='www.vremyanamaza.ru', port=443): Max retries exceeded with url: /%D0%A6%D0%B5%D0%BD%D1%82%D1%80%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9/%D0%B2%D1%80%D0%B5%D0%BC%D1%8F-%D0%BD%D0%B0%D0%BC%D0%B0%D0%B7%D0%B0-%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0/19400-tat17 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103b72b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) 

